name: Auto Upload FB Bot

on:
  schedule:
    - cron: '0 5,10,15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # KEMBALIKAN FFmpeg (Wajib untuk perbaikan struktur video & kompresi)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp requests

      - name: Create Cookies File
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Jalankan Bot Upload
        env:
          FB_PAGES_CONFIG: ${{ secrets.FB_PAGES_CONFIG }}
        run: python bot_upload.py

      - name: Commit & Push Perubahan
        run: |
          git config --global user.name "Bot Upload"
          git config --global user.email "bot@github.com"
          git add videos.txt processed_log.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸ¤– Bot: Update antrian" && git push)
          
